import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
from database import get_subscribers_for_coin

# Load environment configurations
load_dotenv()

# Read SMTP configuration from environmental secrets
ENABLE_EMAIL = os.getenv("ENABLE_EMAIL", "False").lower() in ("true", "1")
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")

def send_alert(coin_id, price_usd, anomaly_type, percent_deviation):
    """
    Retrieves active subscribers mapped specifically to this coin and notifies them of price anomalies.
    Dispatches via secure SMTP mail if enabled, or fallback logs to console.
    """
    subscribers = get_subscribers_for_coin(coin_id)
    
    # 1. Fallback to Console Alert if no subscribers or email disabled
    if not subscribers:
        print(f"[ALERT] No active email subscribers registered for {coin_id.upper()} alerts.")
        print(f"[ALERT] {coin_id.upper()} {anomaly_type.upper()}! Price: ${price_usd:,.2f} (Dev: {percent_deviation:+.2f}%)")
        return
        
    print(f"[Notifier] Preparing alerts for {len(subscribers)} subscribers watching {coin_id.upper()}...")
    
    # Create email content (Subject has emoji, body has details)
    # Note: Terminal prints do not include emoji to prevent Windows terminal encoding crashes.
    subject = f"🚨 CRYPTO ALERT: {coin_id.capitalize()} {anomaly_type.upper()} Detected!"
    
    body = f"""
    Hello Subscriber,
    
    Our automated data pipeline has detected a price anomaly for {coin_id.capitalize()} ({coin_id.upper()}).
    
    - Anomaly Category: {anomaly_type.upper()} (Price moved beyond the 2% threshold)
    - Latest Ingested Price: ${price_usd:,.4f}
    - Deviation from Average: {percent_deviation:+.2f}%
    
    This is an automated alert generated by your Crypto Price Tracker Pipeline.
    To stop receiving these alerts, unsubscribe via the dashboard.
    """
    
    # Check if SMTP configuration is missing
    missing_secrets = not SENDER_EMAIL or not SENDER_PASSWORD
    
    if not ENABLE_EMAIL or missing_secrets:
        # Fallback console log warnings
        if missing_secrets and ENABLE_EMAIL:
            print("[Notifier] WARNING: Email enabled but credentials (SENDER_EMAIL/PASSWORD) are missing in .env.")
            
        print(f"[ALERT] [EMAIL FALLBACK] Sending anomaly log notification to {coin_id.upper()} watchers:")
        for email in subscribers:
            print(f"  - To: {email}")
        print(f"  - Subject: {subject}")
        print(f"  - Details: {anomaly_type.upper()} on {coin_id.upper()} at ${price_usd:,.2f} ({percent_deviation:+.2f}%)")
        return
        
    # 2. Establish Secure SMTP Mail Dispatch
    try:
        # Connect to Gmail SMTP Server and negotiate TLS security
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=10)
        server.starttls() # Secure connection via Transport Layer Security
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        
        # Dispatch individual emails for subscriber privacy
        for email in subscribers:
            msg = MIMEMultipart()
            msg["From"] = SENDER_EMAIL
            msg["To"] = email
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain"))
            
            server.sendmail(SENDER_EMAIL, email, msg.as_string())
            print(f"[Notifier] Email successfully sent to {email} for {coin_id.upper()}")
            
        server.quit()
        
    except Exception as e:
        print(f"[Notifier] ERROR: Failed to send email via SMTP: {e}")

if __name__ == "__main__":
    print("[Notifier] Testing dynamic alert dispatcher...")
    # Initialize database tables and add subscriber if running standalone
    from database import init_db, subscribe_email_to_coin
    init_db()
    subscribe_email_to_coin("test_candidate@gmail.com", "bitcoin", "BTC")
    send_alert("bitcoin", 68500.0, "spike", 3.4)
